name: eduapp
description: "Цифровой помощник педогога"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
#  kiosk_mode: ^0.5.0+2
  nfc_manager: ^3.2.0
  flutter_spinkit: ^5.2.1
  audioplayers: ^6.0.0
  flutter_automation: ^2.0.0
  csv: ^6.0.0
  intl: ^0.19.0
  volume_controller: ^2.0.7

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/quiz-16-03-2023/
    - assets/quiz-space/
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/buttons/
    - assets/quizes/russia/
    - assets/quizes/russia/audio/
    - assets/quizes/russia/images/

